
/* Drop Tables */

DROP TABLE BLOG_ATTACHFILE CASCADE CONSTRAINTS;
DROP TABLE BLOG_AUTHORITY_MEMBER CASCADE CONSTRAINTS;
DROP TABLE BLOG_MENU_AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE BLOG_AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE BLOG_MEMBER CASCADE CONSTRAINTS;
DROP TABLE BLOG_MENU CASCADE CONSTRAINTS;
DROP TABLE BLOG_MULTI_BOARD CASCADE CONSTRAINTS;




/* Create Tables */

-- 파일 정보
CREATE TABLE BLOG_ATTACHFILE
(
	-- 첨부파일 일련번호
	ATTACHFILE_SEQ varchar2(40) NOT NULL,
	-- 첨부파일 유형
	ATTACHFILE_TYPE varchar2(40),
	-- 원본 파일명
	ORGINALFILE_NAME varchar2(200) NOT NULL,
	-- 첨부 파일명
	PHYSICALFILE_NAME varchar2(200) NOT NULL,
	-- 첨부파일 저장경로
	ATTACHFILE_PATH varchar2(500),
	-- 첨부파일 크기
	ATTACHFILE_SIZE number,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (ATTACHFILE_SEQ)
);


-- 권한 종류
CREATE TABLE BLOG_AUTHORITY
(
	-- 권한 코드
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 명칭
	NAME varchar2(1000) NOT NULL,
	-- 코드설명
	DESCRIPTION varchar2(1000),
	-- 사용 여부
	USE_YN varchar2(40) NOT NULL,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (AUTHORITY_ID)
);


-- 사용자별 권한들
CREATE TABLE BLOG_AUTHORITY_MEMBER
(
	-- 권한 코드
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 회원_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	UNIQUE (AUTHORITY_ID, MEMBER_SEQ)
);


-- 회원정보
CREATE TABLE BLOG_MEMBER
(
	-- 회원_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	-- EMAIL
	EMAIL varchar2(1000),
	-- 암호
	PASSWORD varchar2(100) NOT NULL,
	-- 지역
	Adress varchar2(1000),
	-- 관심분야
	Interest varchar2(1000) DEFAULT '없음',
	-- 암호화된 암호
	CRYPT_PASSWORD varchar2(100),
	-- 회원 탈퇴 여부
	MEMBER_YN varchar2(40) DEFAULT 'N' NOT NULL,
	PRIMARY KEY (MEMBER_SEQ)
);


-- 메뉴 마스터 정보
CREATE TABLE BLOG_MENU
(
	-- 메뉴 코드 SEQ
	MENU_SEQ varchar2(40) NOT NULL,
	-- 명칭
	NAME varchar2(1000) NOT NULL,
	-- 정렬순서
	ORDER_NUMBER number DEFAULT 1 NOT NULL,
	-- 메뉴 주소
	MENU_URI varchar2(500),
	-- 사용 여부
	USE_YN varchar2(40),
	PRIMARY KEY (MENU_SEQ)
);


-- 메뉴 따른 권한
CREATE TABLE BLOG_MENU_AUTHORITY
(
	-- 권한 코드
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 메뉴 코드 SEQ
	MENU_SEQ varchar2(40) NOT NULL,
	UNIQUE (AUTHORITY_ID, MENU_SEQ)
);


-- 멀티게시판
CREATE TABLE BLOG_MULTI_BOARD
(
	-- 게시물 일련번호
	MULTI_BOARD_SEQ varchar2(40) NOT NULL,
	-- 제목
	TITLE varchar2(4000),
	-- 내용/댓글
	CONTENT varchar2(4000) NOT NULL,
	-- 시작일시 (공지 등)
	START_DATE varchar2(20),
	-- 종료일시 (공지 등)
	END_DATE varchar2(20),
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	-- 게시판 사용 여부
	BOARD_YN varchar2(40) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_MULTI_BOARD_REAL PRIMARY KEY (MULTI_BOARD_SEQ)
);



/* Create Foreign Keys */

ALTER TABLE BLOG_AUTHORITY_MEMBER
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES BLOG_AUTHORITY (AUTHORITY_ID)
;


ALTER TABLE BLOG_MENU_AUTHORITY
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES BLOG_AUTHORITY (AUTHORITY_ID)
;


ALTER TABLE BLOG_AUTHORITY_MEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES BLOG_MEMBER (MEMBER_SEQ)
;


ALTER TABLE BLOG_MENU_AUTHORITY
	ADD FOREIGN KEY (MENU_SEQ)
	REFERENCES BLOG_MENU (MENU_SEQ)
;



/* Comments */

COMMENT ON TABLE BLOG_ATTACHFILE IS '파일 정보';
COMMENT ON COLUMN BLOG_ATTACHFILE.ATTACHFILE_SEQ IS '첨부파일 일련번호';
COMMENT ON COLUMN BLOG_ATTACHFILE.ATTACHFILE_TYPE IS '첨부파일 유형';
COMMENT ON COLUMN BLOG_ATTACHFILE.ORGINALFILE_NAME IS '원본 파일명';
COMMENT ON COLUMN BLOG_ATTACHFILE.PHYSICALFILE_NAME IS '첨부 파일명';
COMMENT ON COLUMN BLOG_ATTACHFILE.ATTACHFILE_PATH IS '첨부파일 저장경로';
COMMENT ON COLUMN BLOG_ATTACHFILE.ATTACHFILE_SIZE IS '첨부파일 크기';
COMMENT ON COLUMN BLOG_ATTACHFILE.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN BLOG_ATTACHFILE.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN BLOG_ATTACHFILE.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN BLOG_ATTACHFILE.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE BLOG_AUTHORITY IS '권한 종류';
COMMENT ON COLUMN BLOG_AUTHORITY.AUTHORITY_ID IS '권한 코드';
COMMENT ON COLUMN BLOG_AUTHORITY.NAME IS '명칭';
COMMENT ON COLUMN BLOG_AUTHORITY.DESCRIPTION IS '코드설명';
COMMENT ON COLUMN BLOG_AUTHORITY.USE_YN IS '사용 여부';
COMMENT ON COLUMN BLOG_AUTHORITY.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN BLOG_AUTHORITY.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN BLOG_AUTHORITY.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN BLOG_AUTHORITY.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE BLOG_AUTHORITY_MEMBER IS '사용자별 권한들';
COMMENT ON COLUMN BLOG_AUTHORITY_MEMBER.AUTHORITY_ID IS '권한 코드';
COMMENT ON COLUMN BLOG_AUTHORITY_MEMBER.MEMBER_SEQ IS '회원_SEQ';
COMMENT ON TABLE BLOG_MEMBER IS '회원정보';
COMMENT ON COLUMN BLOG_MEMBER.MEMBER_SEQ IS '회원_SEQ';
COMMENT ON COLUMN BLOG_MEMBER.EMAIL IS 'EMAIL';
COMMENT ON COLUMN BLOG_MEMBER.PASSWORD IS '암호';
COMMENT ON COLUMN BLOG_MEMBER.Adress IS '지역';
COMMENT ON COLUMN BLOG_MEMBER.Interest IS '관심분야';
COMMENT ON COLUMN BLOG_MEMBER.CRYPT_PASSWORD IS '암호화된 암호';
COMMENT ON COLUMN BLOG_MEMBER.MEMBER_YN IS '회원 탈퇴 여부';
COMMENT ON TABLE BLOG_MENU IS '메뉴 마스터 정보';
COMMENT ON COLUMN BLOG_MENU.MENU_SEQ IS '메뉴 코드 SEQ';
COMMENT ON COLUMN BLOG_MENU.NAME IS '명칭';
COMMENT ON COLUMN BLOG_MENU.ORDER_NUMBER IS '정렬순서';
COMMENT ON COLUMN BLOG_MENU.MENU_URI IS '메뉴 주소';
COMMENT ON COLUMN BLOG_MENU.USE_YN IS '사용 여부';
COMMENT ON TABLE BLOG_MENU_AUTHORITY IS '메뉴 따른 권한';
COMMENT ON COLUMN BLOG_MENU_AUTHORITY.AUTHORITY_ID IS '권한 코드';
COMMENT ON COLUMN BLOG_MENU_AUTHORITY.MENU_SEQ IS '메뉴 코드 SEQ';
COMMENT ON TABLE BLOG_MULTI_BOARD IS '멀티게시판';
COMMENT ON COLUMN BLOG_MULTI_BOARD.MULTI_BOARD_SEQ IS '게시물 일련번호';
COMMENT ON COLUMN BLOG_MULTI_BOARD.TITLE IS '제목';
COMMENT ON COLUMN BLOG_MULTI_BOARD.CONTENT IS '내용/댓글';
COMMENT ON COLUMN BLOG_MULTI_BOARD.START_DATE IS '시작일시 (공지 등)';
COMMENT ON COLUMN BLOG_MULTI_BOARD.END_DATE IS '종료일시 (공지 등)';
COMMENT ON COLUMN BLOG_MULTI_BOARD.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN BLOG_MULTI_BOARD.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN BLOG_MULTI_BOARD.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN BLOG_MULTI_BOARD.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN BLOG_MULTI_BOARD.BOARD_YN IS '게시판 사용 여부';



